#!/bin/bash

function join_by { local IFS="$1"; shift; echo "$*" }

DOWNLOAD_DIR=download-$(date +%Y-%m-%d_%H:%M:%S)
mkdir $DOWNLOAD_DIR

python3 docker/run_docker.py \
  --fasta_paths=$(join_by , FASTAs/Multimers/*) \
  --model_preset=multimer \
  --data_dir=$DOWNLOAD_DIR

# How do I get the data back on my local machine?
