#!/bin/bash

case "$1" in
  "unit")
    npx jest --testPathPattern=test/unit/ --verbose --silent
    ;;
  "integration")
    npx jest --testPathPattern=test/integration/ --verbose
    ;;
  "system")
    npx jest --testPathPattern=test/integration/system.test.js --verbose --detectOpenHandles
    ;;
  "watch")
    npx jest --watch
    ;;
  "pytest")
    python -m pytest test/ -v
    ;;
  "pytest:debug")
    python -m debugpy --listen 5678 --wait-for-client -m pytest test/ -v -s
    ;;
  "fixtures")
    npx jest --testPathPattern=test/fixtures
    ;;
  *)
    echo "Running all test suites..."
    npx jest --testPathPattern=test/unit/unit.test.js --verbose --silent && npx jest --testPathPattern=test/integration/integration.test.js --verbose && npx jest --testPathPattern=test/integration/system.test.js --verbose --detectOpenHandles
    ;;
esac 