name: molecular_analyzer
description: "A molecular analysis application."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State management
  provider: ^6.0.5
  
  # Camera functionality
  camera: ^0.10.5+5
  image_picker: ^1.0.4
  
  # Payments
  flutter_stripe: ^9.4.0
  
  # HTTP requests
  http: ^1.1.0
  
  # Local storage
  shared_preferences: ^2.2.2
  
  # 3D visualization
  flutter_gl: ^0.0.19
  vector_math: ^2.1.4
  
  # SVG support - NEW
  flutter_svg: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

# Assets folder - NEW
flutter:
  uses-material-design: true
  
  assets:
    - assets/ 