#!/bin/bash

chmod 755 setup-running-docker-as-non-root-user
./setup-running-docker-as-non-root-user

git clone https://github.com/deepmind/alphafold.git

cd alphafold
chmod 755 scripts/download_all_data.sh
./scripts/download_all_data.sh ..
docker build -f docker/Dockerfile -t alphafold .
python3 -m venv alphafold-env
source alphafold-env/bin/activate
pip3 install -r docker/requirements.txt
cd ..

chmod 755 predict
./predict
